version: "3.9"

services:
  openhab:
    container_name: openHAB
    image: "openhab/openhab:3.0.2"
    restart: always
    depends_on:
      - db
      - grafana
      - mosquitto
    # network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - openhab_addons:/openhab/addons
      - openhab_config:/openhab/conf
      - openhab_userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      CRIPTO_POLICY: "unlimited"
    ports:
      - "8080:8080"
      - "8443:8443"

  db:
    container_name: influxdb
    image: "arm32v7/influxdb:1.8"
    ports:
      - "8086:8086"
    restart: always
    env_file: docker/influx/.env
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.7
    # env_file: docker/grafana/.env
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_home:/usr/share/grafana
      - grafana_log:/var/log/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - grafana_provisioning:/etc/grafana/provisioning

  mosquitto:
    container_name: mosquitto
    env_file: docker/mosquitto/.env
    # build:
    #   context: .
    #   dockerfile: dockerfile.mosquitto
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - mosquitto_config:/mosquitto/config

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:v1.7.0
    ports:
      - "81:80"
    restart: always
    volumes:
      - tasmoadmin_data:/data

volumes:
  openhab_addons:
  openhab_config:
  openhab_userdata:
  influxdb_data:
  grafana_data:
  grafana_home:
  grafana_log:
  grafana_plugins:
  grafana_provisioning:
  mosquitto_data:
  mosquitto_log:
  mosquitto_config:
  tasmoadmin_data:
