version: "3.9"

services:
  db:
    container_name: influxdb
    image: "arm32v7/influxdb:2.0"
    ports:
      - "8086:8086"
    restart: always
    env_file: docker/influxdb/.env
    volumes:
      - type: volume
        source: ./volumes/influxdb/db_data
        target: /var/lib/influxdb
    secrets:

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.6
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5"
      GF_SECURITY_ADMIN_USER__FILE: "/run/secrets/grafana_admin_user"
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/grafana_admin_password"
      GF_USERS_DßEFAULT_THEME: "dark"
      GF_SERVER_DOMAIN: "localhost"
      GF_SERVER_ROOT_URL: "http://localhost:3000/grafana"
    config:
      - source: grafana-config
        target: /etc/grafana/grafana.ini
    volumes:
      - type: bind
        source: ./grafana/data
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/logs
        target: /var/log/grafana
      - type: bind
        source: ./grafana/plugins
        target: /var/lib/grafana/plugins
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
    secrets:
      - grafana_admin_user
      - grafana_admin_password

  mosquitto:
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    build:
      context: .
      dockerfile: dockerfile.mosquitto
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    container_name: mosquitto
    env_file: docker/mosquitto/.env
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
    volumes:
      - type: bind
        source: ./mosquitto/data
        target: /mosquitto/data
      - type: bind
        source: ./mosquitto/log
        target: /mosquitto/log
      - type: bind
        source: ./mosquitto/config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - type: bind
        source: ./docker/mosquitto/docker-entrypoint.sh
        target: /docker-entrypoint-initdb.d/docker-entrypoint.sh

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:v1.7.0
    ports:
      - "81:80"
    restart: always
    volumes:
      - type: bind
        source: ./tasmoadmin/data
        target: /data

secrets:
  influx_user:
    file: "./docker/influx/secrets/influx_user"
  influx_passwd:
    file: "./docker/influx/secrets/influx_passwd"
  grafana_admin_user:
    file: "./sectrets/grafana/grafana_admin_user"
  grafana_admin_password:
    file: "./sectrets/grafana/grafana_admin_password"
