version: "3"

services:
  influxdb:
    image: arm32v7/influxdb:1.8
    ports:
      - "8086:8086"
    restart: always
    volumes: 
      - influxdb_data:/var/lib/influxdb_data

volumes:
  influxdb_data: