FROM eclipse-mosquitto:2

VOLUME [ "/mosquitto/config" ]

# Sets the mosquitto for authentication
RUN touch /mosquitto/config/mosquitto.passwd
COPY docker/mosquitto/config/mosquitto.conf /mosquitto/config/

RUN mosquitto_passwd -b /mosquitto/config/mosquitto.passwd openhab openhab

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]