version: "3"

services:
  openhab:
    container_name: openHAB
    image: "openhab/openhab:3.0.2"
    restart: always
    depends_on:
      - influxdb
      - grafana
    # network_mode: host
    networks:
      - openhab
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openHAB/addons:/openhab/addons"
      - "./openHAB/conf:/openhab/conf"
      - "./openHAB/userdata:/openhab/userdata"
      - "./openHAB/services:/etc/openhab/services"
      - "./cont-init.d:/etc/cont-init.d"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      CRIPTO_POLICY: "unlimited"
      # USER_ID: 9001
      # GROUP_ID: 9001
    ports:
      - "8080:8080"
      - "8443:8443"

  influxdb:
    container_name: influxdb
    image: "influxdb:1.8"
    ports:
      - "8086:8086"
    restart: always
    networks:
      - openhab
    volumes:
      - "./influxdb/db_data:/var/lib/influxdb_data"
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - openhab
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5"
      GF_SECURITY_ADMIN_PASSWORD__FILE: "./secrets/admin_password"
    volumes:
      - "./grafana/data:/var/lib/grafana"
      - "./grafana/config/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/logs:/var/log/grafana"
      - "./grafana/plugins:/var/lib/grafana/plugins"

networks:
  openhab:
