version: "3.9"

services:
  nginx:
    container_name: nginx:1
    image: nginx
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf:ro
      - type: bind
        source: ./nginx/www
        target: /html:ro
      - type: bind
        source: ./nginx/nginx-ssl.crt
        target: /etc/nginx/chained.crt:ro
      - type: bind
        source: ./nginx/nginx-ssl.key
        target: /etc/nginx/key.key:ro
      - type: bind
        source: ./nginx/htpasswd
        target: /etc/nginx/htpasswd:ro

  php:
    container_name: php
    image: php:8-fpm
    restart: always
    volumes:
      - type: bind
        source: ./nginx/www
        target: /html

  openhab:
    container_name: openHAB
    image: "openhab/openhab:3.0.2"
    restart: always
    depends_on:
      - influxdb
      - grafana
    network_mode: host
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime:ro
      # Localtime zone
      # ex: Europe/Berlin
      # You can use also the file located in this directory
      # ./timezone
      - type: bind
        source: /etc/timezone
        # source: ./timezone
        target: /etc/timezone:ro
      - type: bind
        source: ./openHAB/addons
        target: /openhab/addons
      - type: bind
        source: ./openHAB/conf
        target: /openhab/conf
      - type: bind
        source: ./openHAB/userdata
        target: /openhab/userdata
      - type: bind
        source: ./openHAB/services
        target: /etc/openhab/services
      # This is the html location
      # Access with "https://192.168.1.81:8080/static/{html_file_name}"
      - type: bind
        source: ./openHAB/html
        target: /etc/openhab/html
      # Directory for the trasformation JS files
      - type: bind
        source: ./openHAB/trasform
        target: /etc/openhab/trasform
      - type: bind
        source: ./openHAB/backup
        target: /backups
      # - type: bind
      #   source: ./openHAB/cont-init.d
      #   target: /etc/cont-init.d
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      CRIPTO_POLICY: "unlimited"
      USER_ID: 9001
      GROUP_ID: 9001
    ports:
      - "8080:8080"
      - "8443:8443"
    command:

  influxdb:
    container_name: influxdb
    image: "arm32v7/influxdb:1.8"
    ports:
      - "8086:8086"
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: "openhabinfluxdb"
      DOCKER_INFLUXDB_INIT_PASSWORD: "openhabinfluxdb"
      # DOCKER_INFLUXDB_INIT_USERNAME__FILE: "/run/secrets/influxdb_admin_user"
      # DOCKER_INFLUXDB_INIT_PASSWORD__FILE: "/run/secrets/influxdb_admin_password"
    volumes:
      - type: bind
        source: ./influxdb/db_data
        target: /var/lib/influxdb_data
      - type: bind
        source: ./influxdb/influxdb.conf
        target: /etc/influxdb/influxdb.conf
    # secrets:
    #   - influxdb_admin_user
    #   - influxdb_admin_password

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5"
      GF_SECURITY_ADMIN_USER__FILE: "/run/secrets/grafana_admin_user"
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/grafana_admin_password"
      GF_USERS_DEFAULT_THEME: "dark"
      GF_SERVER_DOMAIN: "localhost"
      GF_SERVER_ROOT_URL: "http://localhost:3000/grafana"
    volumes:
      - type: bind
        source: ./grafana/data
        target: /var/lib/grafana
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./grafana/logs
        target: /var/log/grafana
      - type: bind
        source: ./grafana/plugins
        target: /var/lib/grafana/plugins
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
    secrets:
      - grafana_admin_user
      - grafana_admin_password

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # We bind the entire config file for mosquitto
      # for integrate the './mosquitto/config/mosquitto.conf' file
      - type: bind
        source: ./mosquitto/config
        target: /mosquitto/config
      # We bind the passwd for the user
      - type: bind
        source: ./mosquitto/config/mosquitto.passwd
        target: /mosquitto/config/mosquitto.passwd
      - type: bind
        source: ./mosquitto/data
        target: /mosquitto/data
      - type: bind
        source: ./mosquitto/log
        target: /mosquitto/log

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    ports:
      - "81:80"
    restart: always
    volumes:
      - type: bind
        source: ./tasmoadmin/data
        target: /data

secrets:
  influxdb_admin_user:
    file: "./sectrets/influxdb/influxdb_admin_user"
  influxdb_admin_password:
    file: "./sectrets/influxdb/influxdb_admin_password"
  grafana_admin_user:
    file: "./sectrets/grafana/grafana_admin_user"
  grafana_admin_password:
    file: "./sectrets/grafana/grafana_admin_password"
