version: "3.9"

services:
  db:
    container_name: influxdb
    image: "arm32v7/influxdb:1.8"
    ports:
      - "8086:8086"
    restart: always
    env_file: docker/influx/.env
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.2
    # env_file: docker/grafana/.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_home:/usr/share/grafana
      - grafana_log:/var/log/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - grafana_provisioning:/etc/grafana/provisioning

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    # env_file: docker/mosquitto/.env
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - mosquitto_config:/mosquitto/config

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:v1.7.0
    ports:
      - "81:80"
    restart: always
    volumes:
      - tasmoadmin_data:/data

volumes:
  influxdb_data:
  grafana_data:
  grafana_home:
  grafana_log:
  grafana_plugins:
  grafana_provisioning:
  mosquitto_data:
  mosquitto_log:
  mosquitto_config:

secrets:
  # Influx
  influx_user:
    file: "./docker/influx/secrets/influx_user"
  influx_passwd:
    file: "./docker/influx/secrets/influx_passwd"
  influx_admin_user:
    file: "./docker/influx/secrets/influx_admin_user"
  influx_admin_passwd:
    file: "./docker/influx/secrets/influx_admin_passwd"
#------------------------------------------------------------#
# version: "3.9"

# services:
#   openhab:
#     container_name: openHAB
#     image: "openhab/openhab:3.0.2"
#     restart: always
#     depends_on:
#       - influxdb
#       - grafana
#       - mosquitto
#     network_mode: host
#     volumes:
#       - type: bind
#         source: /etc/localtime
#         target: /etc/localtime:ro
#       # Localtime zone
#       # ex: Europe/Berlin
#       # You can use also the file located in this directory
#       # ./timezone
#       - type: bind
#         source: /etc/timezone
#         target: /etc/timezone:ro
#       - type: bind
#         source: ./openHAB/addons
#         target: /openhab/addons
#       - type: bind
#         source: ./openHAB/conf
#         target: /openhab/conf
#       - type: bind
#         source: ./openHAB/userdata
#         target: /openhab/userdata
#       - type: bind
#         source: ./openHAB/services
#         target: /etc/openhab/services
#       # This is the html location
#       # Access with "https://192.168.1.81:8080/static/{html_file_name}"
#       - type: bind
#         source: ./openHAB/html
#         target: /etc/openhab/html
#       # Directory for the trasformation JS files
#       - type: bind
#         source: ./openHAB/trasform
#         target: /etc/openhab/trasform
#       - type: bind
#         source: ./openHAB/backup
#         target: /backups
#       # - type: bind
#       #   source: ./openHAB/cont-init.d
#       #   target: /etc/cont-init.d
#     environment:
#       OPENHAB_HTTP_PORT: "8080"
#       OPENHAB_HTTPS_PORT: "8443"
#       EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
#       CRIPTO_POLICY: "unlimited"
#       USER_ID: 9001
#       GROUP_ID: 9001
#     ports:
#       - "8080:8080"
#       - "8443:8443"
