version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: "influxdb:2.0"
    ports:
      - "8086:8086"
    restart: always
    network_mode: bridge
    env_file: docker/influxdb/.env
    volumes:
      - type: bind
        source: ./influxdb/db_data
        target: /var/lib/influxdb
      - type: bind
        source: ./influxdb/config/influxdb.conf
        target: /etc/influxdb/influxdb.conf
      - type: bind
        source: ./influxdb/scripts
        target: /docker-entrypoint-initdb.d/
    command: ["sh", "/init-influxdb.sh"]
