FROM eclipse-mosquitto:2

# Sets the mosquitto for authentication
COPY docker/mosquitto/config/mosquitto.conf /mosquitto/config/mosquitto.conf

RUN touch /mosquitto/config/mosquitto.passwd && mosquitto_passwd -b /mosquitto/config/mosquitto.passwd openhab openhab

VOLUME [ "/mosquitto/config" ]
