services:
  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin:v1.7.0
    ports:
      - "81:80"
    restart: always
    volumes:
      - type: bind
        source: ./tasmoadmin/data
        target: /data
