apiVersion: 1

deleteDatasources:
  - name: MYINFLUX
    orgId: 1

datasources:
  - name: openHABInfluxdb
    type: influxdb
    access: proxy
    url: http://influxdb
    user: openhab
    password: openhab
    database: openhab3
    basicAuth: false
    # basicAuthUser:
    # basicAuthPassword:
    # withCredentials:
    isDefault: true
    jsonData:
      httpMode: POST
      tlsAuth: false
      tlsAuthWithCACert: false
    # secureJsonData:
    #   tlsCACert: ""
    #   tlsClientCert: ""
    #   tlsClientKey: ""
    version: 1
    editable: true
